/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package statesandcapitals;

import java.io.IOException;
import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    ArrayList<Integer> list = new ArrayList<>();
//    StatesAndCapitals test1 = new StatesAndCapitals();
    public static void main(String[] args)  {
        System.out.println(new App().getGreeting());

    }
}
